---
version: '3.7'

services:
  app:
    image: 'php:8.0-cli-alpine'
    working_dir: '/var/www/html'
    command: ['php', '-S', '0.0.0.0:8888', '-t', '/var/www/html']
    ports:
      - '8888:8888'
    volumes:
      - ./app:/var/www/html